### ISSUE TITLE
anyone has this error?

### ISSUE THREAD

**Issue by Parakovsky** [daedalus1337/red#12] opened 2022-10-27 10:31 UTC
since this amazing man added some functionality my copy of the program always returns 

Traceback (most recent call last):
  File "red.py", line 1, in <module>
    import actions
  File "/home/user/red2/red/actions.py", line 13
    print(f"Status of request is {req.status_code}. Aborting...")
                                                               ^
SyntaxError: invalid syntax

no matter what I do, curious how to fix this

**Comment by daedalus1337** [comment] 2022-10-28 08:10
Hey now!  I'm taking a look at this now.  When you get a chance, can you confirm if this happens when you run "inbox" or "stats"?  My thought right now is that they'll work, and that your issues are isolated to the search and download functions.

**Comment by daedalus1337** [comment] 2022-10-28 08:34
Ok, thinking about it more after a few more sips of my third massive infusion of caffeine for the day, I'm realizing that you're going to have the problem on all functions.  The problem isn't line 13, or even what's happening in that entire block of code.  Line 13 only even matters if your API requests aren't working in the first place.  I'm suspicious that there is an issue with your config file.  I'm going to just vomit out a couple of ideas.

1) if you're using Windows and editing with VS Code, make sure the files are set to LF and not CRLF.  This messes with white space and will absolutely cause nightmares.
2) if you added in the toplist_limit parameter manually in the config, make sure you added a comma to the end of the line before it.  It'll definitely give you an error, but I'm not sure if it's the issue here.

Let me know if those things help.  If not, I'll push up some code that'll help us debug, then once we figure it out, I'll push up more code to make sure it's easier to identify the issue in the future :P.

**Comment by daedalus1337** [comment] 2022-12-08 01:03
based on other conversations outside of github, it sounds like these problems were resolved by the latest major update

**Closed by daedalus1337** 2022-12-08 01:03 UTC
